[platformio]
src_dir = .

[env:m5cardputer]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags = -DCORE_DEBUG_LEVEL=2 #{Non,Err,Wrn,Inf,Dbg,Ver}
lib_deps = 
	m5stack/M5GFX
	m5stack/M5Unified
	m5stack/M5Cardputer
	bblanchon/ArduinoJson

board_build.embed_files = 
	assets/cards/00-the-fool.png
	assets/cards/01-the-magician.png
	assets/cards/02-the-high-priestess.png
	assets/cards/03-the-empress.png
	assets/cards/04-the-emperor.png
	assets/cards/05-the-hierophant.png
	assets/cards/06-the-lovers.png
	assets/cards/07-the-chariot.png
	assets/cards/08-strength.png
	assets/cards/09-the-hermit.png
	assets/cards/10-wheel-of-fortune.png
	assets/cards/11-justice.png
	assets/cards/12-the-hanged-man.png
	assets/cards/13-death.png
	assets/cards/14-temperance.png
	assets/cards/15-the-devil.png
	assets/cards/16-the-tower.png
	assets/cards/17-the-star.png
	assets/cards/18-the-moon.png
	assets/cards/19-the-sun.png
	assets/cards/20-judgement.png
	assets/cards/21-the-world.png
	assets/cards/back.png
